version: '3.1'
services:
  localstack:
    build:
      context: ./localstack
    environment:
      - SERVICES=s3,dynamodb,sqs
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_HOST=localhost
      - PERSISTENCE=/tmp/localstack/data
      - DYNAMODB_SHARE_DB=1
      - ALLOW_NONSTANDARD_REGIONS=1
    ports:
      # Edge
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
